# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  default_branch: main
  delete_branch_on_merge: true
  topics: code-management

teams:
  - name: code-management
    permission: admin

branches:
  - name: main
    protection:
      required_pull_request_reviews: # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
        required_approving_review_count: 1 # The number of approvals required. (1-6)
        dismiss_stale_reviews: false # Dismiss approved reviews automatically when a new commit is pushed.
        require_code_owner_reviews: true # Blocks merge until code owners have reviewed.
        dismissal_restrictions: # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
          users: []
          teams: []

      required_status_checks: # Required. Require status checks to pass before merging. Set to null to disable
        strict: true # Required. Require branches to be up to date before merging.
        contexts: [] # Required. The list of status checks to require in order to merge into this branch

      enforce_admins: true # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      restrictions: null # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
