version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0
  shellcheck: circleci/shellcheck@3.1
  change-api: financial-times/change-api@1.0.8

references:
  filters: &filters
    tags:
      only: /.*/
  filters_version_tag: &filters_version_tag
    branches:
      ignore: /.*/
    tags:
      only:
        - /^v?\d+\.\d+\.\d+$/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
          exclude: "RC006, RC010" # excluding RC006 as the GitHub repo is private, exluding RC0010 as parameters do not pass validation in orb-tools.
      - shellcheck/check:
          filters: *filters
      - orb-tools/publish:
          orb_name: financial-times/doppler-circleci
          vcs_type: << pipeline.project.type >>
          requires:
            - orb-tools/lint
            - orb-tools/review
            - orb-tools/pack
            - shellcheck/check
          # Use a context to hold your publishing token.
          context: circleci-orb-publishing
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: doppler-circleci
          requires: [orb-tools/publish]
          filters: *filters
      # Data for sending to change-api
      - change-api/change-log:
          name: doppler-circleci-orb-prod
          filters:
            <<: *filters_version_tag
          context: change-api-orb
          system-code: doppler-circleci-orb
          environment: prod
          slack-channels: ft-changes, cm-alerts

