description: >
  An example of a multi-environment workflow that loads secrets from different doppler configs in two separate jobs.
  Note a Doppler service token is required for each environment.
usage:
  version: 2.1
  orbs:
    doppler-circleci: ft-circleci-orbs/doppler-circleci@1.3
  jobs:
    load_secrets_for_staging_deployment:
      docker:
        - image: cimg/base:current
      steps:
        - doppler-circleci/install
        - doppler-circleci/load_secrets:
            doppler_token: DOPPLER_TOKEN_STAGING
        - run: echo -e "${SUPER_SECRET_PASSWORD}"
    load_secrets_for_prod_deployment:
      docker:
        - image: cimg/base:current
      steps:
        - doppler-circleci/install
        - doppler-circleci/load_secrets:
            doppler_token: DOPPLER_TOKEN_PROD
        - run: echo -e "${SUPER_SECRET_PASSWORD}"
  workflows:
    setup:
      jobs:
        - load_secrets_for_staging_deployment
        - load_secrets_for_prod_deployment
